posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('forgot_password/', views.forgot, name="forgot"),
    path('recover_password/', views.recover, name="recover"),
    path("posts/like/", views.likeapost, name="likeapost"),
    path("comments/like/", views.likeacomment, name="likeacomment"),
    path("comments/delete/", views.deleteacomment, name="deleteacomment"),
    path("posts/delete/", views.deletepost, name="deletepost"),
    path("posts/add", views.post_a_Post, name="addpost"),
    path("posts/<slug>/details", views.PostDetailView.as_view(), name="single_post"),
    path("posts/<pk>/details/comment", views.AddComment, name="comment_post"),
]

yieldUp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('diagonise/', include('diagnosis.urls')),
    path('doctors/', include('doctor.urls')),
    path('users/', include('profiler.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

posts/models.py
from django.db import models
from django.contrib import messages
from django.contrib.auth.models import AbstractBaseUser, User
from django.core.validators import validate_image_file_extension, FileExtensionValidator, validate_email, validate_slug, URLValidator
# from django.core.mail import send_mail
from django.dispatch import receiver
from django.db.models.signals import post_delete, pre_save
from django.utils.text import slugify


class Post(models.Model):
    """docstring for Post"""
    title = models.CharField(max_length=255)
    body = models.TextField()
    video = models.FileField(upload_to='post_videos', blank=True, null=True)
    posted_on = models.DateTimeField(auto_now_add=True)
    Image = models.ImageField(upload_to='post_images', blank=True, null=True,
                              validators=[validate_image_file_extension])
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True, null=True)
    likes = models.ManyToManyField(
        User, verbose_name='Likes', related_name='Likes', blank=True)

    def __str__(self):
        return self.title

    @ property
    def total_likes(self):
        return self.likes.count()

    @ property
    def total_comments(self):
        return postComment.objects.filter(comment_to=self).count()

    def __unicode__(self):
        return u'%s' % self.title

class postComment(models.Model):
    comment_to = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_by = models.ForeignKey(
        User, related_name='commenter', on_delete=models.CASCADE)
    comment_body = models.TextField(max_length=650)
    comment_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(
        User, verbose_name='Likes', related_name='likecomment', blank=True)

    def __str__(self):
        return self.comment_to.title

    @ property
    def total_likes(self):
        return self.likes.count()

    @ property
    def all_likes(self):
        return self.likes

    @ property
    def total_replies(self):
        return Commentreply.objects.filter(reply_to=self).count()

    def __unicode__(self):
        return u'%s' % self.comment_to.title


class Commentreply(models.Model):
    reply_to = models.ForeignKey(postComment, on_delete=models.CASCADE)
    reply_by = models.ForeignKey(
        User, related_name='replier', on_delete=models.CASCADE)
    reply_body = models.TextField(max_length=200)
    reply_on = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(
        User, verbose_name='Likes', related_name='likereply',  blank=True)

    def __str__(self):
        return self.reply_to.comment_to.title

    @ property
    def total_likes(self):
        return self.likes.count()

    def __unicode__(self):
        return u'%s' % self.reply_to.comment_to.title


@receiver(post_delete, sender=Post)
def submission_delete(sender, instance, **kwargs):
    instance.Image.delete(False)
    instance.video.delete(False)


@receiver(pre_save, sender=Post)
def pre_save_Post_receiver(sender, instance, *args, **kwargs):
    instance.slug = slugify(instance.title)

profiler/models.py
from django.utils import timezone
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_delete, pre_save, post_save
from django.utils.text import slugify

# Create your models here.


class Profile(models.Model):
    """Profile as an extension of the User model"""
    roles = [
        ("dr", "Doctor"),
        ("fr", "Farmer"),
    ]
    role = models.CharField(max_length=10, null=True,
                            blank=True, choices=roles)
    address = models.CharField(max_length=255, null=True, blank=True)
    bio = models.CharField(max_length=2000, null=True, blank=True)
    years_of_experiance = models.PositiveIntegerField(
        default=0, null=True, blank=True)
    added_on = models.DateTimeField(auto_now_add=True)
    stars = models.ManyToManyField(
        User, verbose_name='stars', related_name='stars', blank=True)
    phone_number = models.CharField(null=True, blank=True, max_length=14)
    profile_pik = models.ImageField(
        null=True, blank=True, upload_to="profiles")
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    @property
    def total_stars(self):
        return self.stars.count()

    def __str__(self):
        return self.user.username


# comment this on first migrations


code = str(int(datetime.datetime.timestamp(datetime.datetime.now())))[-6:]
# harmonizing timezones
today = timezone.now()
expire_after_30 = today + timezone.timedelta(minutes=30)


class GenerateCodes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(
        unique=True, max_length=100, default=code)
    generated_on = models.DateTimeField(auto_now=True)
    expires_on = models.DateTimeField(default=expire_after_30)
    reason = models.CharField(max_length=100, null=True, blank=True)

    @property
    def has_expired(self):
        today = timezone.now()
        if today >= self.expires_on:
            return True
        else:
            return False

# signals


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user=kwargs['instance'])


@receiver(pre_save, sender=GenerateCodes)
def BeforeCreateResetPasswordToken(sender, instance=None, **kwargs):
    # token =
    pass


@receiver(post_delete, sender=Profile)
def submission_delete(sender, instance, **kwargs):
    instance.profile_pik.delete(False)

posts/views.py
from django.db.models.query_utils import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, response
from django.views.generic import TemplateView, DetailView

from diagnosis.models import Diagnosis
from .models import Post, postComment, Commentreply
from django.contrib.auth.models import User, auth
from django.contrib.auth.decorators import login_required
# Create your views here.


def index(request):
    if request.user.is_authenticated:
        myposts = Post.objects.all()
        topTests = Diagnosis.objects.all().order_by("?")[:4]
        topPosts = Post.objects.all().order_by("?")[:4]
        return render(request, 'posts/all_posts.html', {'posts': myposts, "tests": topTests, "top_posts": topPosts})
    else:
        return render(request, 'splash.html')


@login_required(login_url='/login/')
def logout(request):
    auth.logout(request)
    return redirect("/")


def login(request):
    if request.is_ajax():
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user_check_point_1 = User.objects.get(
                Q(username=username) | Q(email=username))
            user = auth.authenticate(
                username=user_check_point_1.username, password=password)
            if user is not None:
                auth.login(request, user)
                result = "Login successfull"
                classNow = "success"
            else:
                result = "No member is associated with the given credentials"
                classNow = "danger"
        except User.DoesNotExist:
            result = "The username or email you entered does not exist!"
            classNow = 'danger'

        return JsonResponse({"result": result, "class": classNow}, status=200)
    return render(request, 'auths/login.html')


def register(request):
    if request.is_ajax():
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        password2 = request.POST.get('password2')

        if username == "" or email == "" or password1 == "" or password2 == "" or fname == "" or lname == "":
            result = "Some form fields are still empty"
            classNow = 'danger'
        elif password1 != password2:
            result = "Passwords are not matching"
            classNow = 'danger'
        else:
            if User.objects.filter(username=username).exists():
                result = "The username is already taken"
                classNow = 'warning'
            elif User.objects.filter(email=email).exists():
                result = "The email is associated with some other account"
                classNow = 'warning'
            else:
                user = User.objects.create_user(username=username, password=password2, email=email, first_name=fname,
                                                last_name=lname)
                user.save()
                result = "Account created successfully, you can now login"
                classNow = 'success'

        return JsonResponse({"result": result, "class": classNow}, status=200)
    return render(request, 'auths/register.html')


def forgot(request):
    return render(request, 'auths/forgot_password.html')


def recover(request):
    return render(request, 'auths/recover_password.html')

# class Posts(TemplateView):
# 	# model = Post
# 	template_name = 'posts/all_posts.html'

# 	def get_context_data(self, *args, **kwargs):
# 		context = super().get_context_data(**kwargs)
# 		context['myposts'] = Post.objects.all()
# 		return context


@login_required(login_url='/login/')
def post_a_Post(request):
    if request.method == 'POST' or request.is_ajax():
        Image = request.FILES.get('image')
        video = request.FILES.get('video')
        body = request.POST.get('body')
        title = request.POST.get('title')
        message = ""
        status = False
        if Image is None and video is None and body == '' and title == '':
            message = "Are you submitting an empty post?"
            status = False
        elif Image is not None and video is not None:
            mypost = Post(title=title, body=body,
                          Image=Image, posted_by=request.user)
            mypost.save()
            message = "Only your image was attached."
            status = True
        # elif Image != '' and title != '' and body != '':
        #     mypost = Post(title=title, body=body,
        #                   Image=Image, posted_by=request.user)
        #     mypost.save()
        #     status = True
        # elif video != '' and title != '' and body != '':
        #     mypost = Post(title=title, body=body,
        #                   video=video, posted_by=request.user)
        #     mypost.save()
        #     status = True
        else:
            mypost = Post(title=title, body=body, video=video,
                          Image=Image, posted_by=request.user)
            mypost.save()
            message = "Uploaded successfully"
            status = True
    return JsonResponse({"status": status, "message": message})


@ login_required(login_url='/login/')
def likeapost(request):
    if request.is_ajax():
        post = get_object_or_404(Post, pk=request.GET.get('id'))

        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        countNow = post.total_likes
        return JsonResponse({
            "countNow": countNow,
            "result": 'ok'
        })


@ login_required(login_url='/login/')
def deletepost(request):
    if request.is_ajax():
        post = Post.objects.get(pk=request.GET.get('id'))
        if post.posted_by == request.user:
            mydel = post.delete()
            return JsonResponse({
                "result": 'ok'
            })
        else:
            return JsonResponse({
                "result": 'no'
            })


def AddComment(request, pk):
    if request.method == 'POST':
        if request.is_ajax():
            try:
                myComment = Post.objects.get(pk=pk)
                comment_body = request.POST.get('body')
                comment_fro = request.user
                if comment_body == "":
                    result = "The comment you submitted seems empty!"
                    classNow = 'danger'
                else:
                    mycomm = postComment.objects.create(
                        comment_to=myComment,
                        comment_body=comment_body,
                        comment_by=comment_fro
                    )

                    if mycomm:
                        num = Post.objects.get(pk=pk).total_comments
                        result = "You commented successfully!"
                        classNow = 'success'
                    else:
                        result = "An error occured and your comment was not added!"
                        classNow = 'error'
            except myComment.DoesNotExist:
                result = "The post you are trying to comment on no-longer exists!"
                classNow = 'danger'

    return JsonResponse({"result": result, "class": classNow, "new_num": num}, status=200)


@ login_required(login_url='/login/')
def likeacomment(request):
    if request.is_ajax():
        comment = get_object_or_404(postComment, pk=request.GET.get('id'))

        if comment.likes.filter(id=request.user.id).exists():
            comment.likes.remove(request.user)
        else:
            comment.likes.add(request.user)

        countNow = comment.total_likes
        return JsonResponse({
            "countNow": countNow,
            "result": 'ok'
        })


@ login_required(login_url='/login/')
def deleteacomment(request):
    if request.is_ajax():
        post = get_object_or_404(postComment, pk=request.GET.get('id'))
        try:
            post = postComment.objects.get(pk=request.GET.get('id'))
            mydel = post.delete()
            if mydel:
                mypostNow = Post.objects.get(pk=request.GET.get('post_id'))
                if mypostNow:
                    countNow = mypostNow.total_comments
                    print(countNow)
                    return JsonResponse({
                        "countNow": countNow,
                        "result": 'ok'
                    })
                else:
                    return JsonResponse({
                        "result": 'no'
                    })
            else:
                return JsonResponse({
                    "result": 'no'
                })
        except post.DoesNotExist:
            return JsonResponse({
                "result": 'no'
            })


class PostDetailView(DetailView):
    model = Post
    context_object_name = "post"
    template_name = "posts/single_post.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = postComment.objects.filter(
            comment_to=self.object)
        return context

    # def post()

templates/posts/single_post.html
{% extends 'base.html' %} {% load static %} {% load humanize %} {% block content %}
<!-- {{ full_post }} -->

<section class="content-header">
    <div class="container-fluid">
        <div class="row">

            <div class="post border border-primary text-left  col-lg-8 col-md-5 col-sm-12" style="border-radius: 10px;">
                <div class="user-block mt-1">
                    {% if post.posted_by.profile.profile_pik.url is not None %}
                    <img class="img-circle img-bordered-sm" src="{{post.posted_by.profile.profile_pik.url}}" alt="{{post.posted_by.username|capfirst}}"> {% else %}
                    <img class="img-circle img-bordered-sm" src="{% static 'images/images.jpg' %}" alt="{{post.posted_by.username|capfirst}}"> {% endif %}
                    <span class="username">

						{% if post.posted_by == user %} You {% else %} <a href="#">{{ post.posted_by.username|capfirst }} {{ post.posted_by.last_name|capfirst }} {{ post.posted_by.first_name|capfirst }}</a>{% endif %}
						<br>
						<a href="{% url 'posts:single_post' post.id %}">{{ post.title|capfirst|truncatechars:200 }}</a>

						<!-- <div class="float-right">
							<a href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class=" bg-secondary btn-tool border" style="border-radius: 20px;"><i class="fas fa-ellipsis-h"></i></a>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
								{% if post.posted_by == user %}
								<a class="dropdown-item btn"><i class="fa fa-edit"></i> Edit</a>
								<a class="dropdown-item btn" data-url="{% url 'posts:deletepost' %}" onclick="deletePost({{post.id}})"><i class="fas fa-minus-circle"></i> Delete</a>
								{% endif %}
								<a href="{% url 'posts:single_post' post.id %}" class="dropdown-item btn"><i class="fas fa-info-circle"></i> Details</a>
							</div>
						</div> -->
					</span>
                    <span class="description">{{ post.posted_on|naturaltime }}</span>
                </div>
                <!-- /.user-block -->
                <div>
                    {{ post.body|safe|truncatewords:20|linebreaks }}
                </div>
                {% if post.Image %}
                <img src="{{ post.Image.url }}" width="100%" class="mb-1"> {% elif post.video %}
                <video src="{{ post.video.url }}" controls width="100%"></video> {% else %} {% endif %}
                <p>
                    <a class="btn bg-dark  text-sm" id="btnLikePost" data-url="{% url 'posts:likeapost' %}" onclick="likepost({{ post.id }})" data-id="{{ post.id }}">
                        <i class="far fa-thumbs-up"> Like</i>
                    </a>
                    <span class="mx-2" id="postLikesTop{{ post.id }}"> {{ post.total_likes }} Like{{ post.total_likes|pluralize }}</span>
                    <span class="float-right">
						<a class="text-sm btn">
							<i class="far fa-comments mr-1"></i> Comments (<span id="numNow">{{post.total_comments}}</span>)
                    </a>
                    </span>
                </p>

                <h3>Leave a comment.</h3>
                <form class="form-horizontal" id="formforComment" method="POST" action="{% url 'posts:comment_post' post.id %}">
                    {% csrf_token %}
                    <div class="input-group input-group-sm mb-0">
                        <textarea class="form-control form-control-sm" style="resize: none;" name="body" placeholder="Response"></textarea>
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-danger"><i class="fas text-lg fa-paper-plane"></i></button>
                        </div>
                    </div>
                </form>


                <!-- comments -->
                <div id="commentSection">
                    {% for comm in comments reversed %}
                    <div class="direct-chat-msg " id="commentbox{{ comm.id }}">
                        <div class="direct-chat-infos clearfix ml-5">
                            {% if user.id == comm.comment_by.id %}
                            <span class="direct-chat-name">You</span> {% else %}
                            <span class="direct-chat-name">{{ comm.comment_by.username|capfirst }} {{ comm.comment_by.last_name|capfirst }}</span> {% endif %}
                        </div>
                        <!-- /.direct-chat-infos -->
                        {% if comm.comment_by.profile.profile_pik %}
                        <a href="{{ comm.comment_by.profile.profile_pik.url }}" target="_blank">
                            <img src="{{ comm.comment_by.profile.profile_pik.url }}" alt="{{ comm.comment_by.username|capfirst }}" class="direct-chat-img">
                        </a>
                        {% else %}
                        <img class="direct-chat-img" src="{% static 'images/images.jpg' %}" alt="{{ comm.comment_by.username|capfirst }}"> {% endif %}

                        <!-- /.direct-chat-img -->
                        <div class="direct-chat-text mb-1">
                            <h6 class="direct-chat-timestamp text-right"><span class="mr-3">{{ comm.comment_on|naturaltime }}</span>
                                <!-- <i class="fa fa-reply" onclick="openreply({{ comm.id }})"></i> -->
                            </h6>

                            <div class="">
                                <a href="" class="text-dark">{{ comm.comment_body|capfirst|linebreaksbr }}</a>
                            </div>
                            <h6 class="text-right">{% if comm.comment_by == user %}
                                <button type="button" id="commentDelete_{{ comm.id }}" data-url="{% url 'posts:deleteacomment' %}" class="btn mr-1 text-light btn-sm btn-danger" onclick="deleteCommentNow({{ comm.id }}, {{ post.id }})"><i
                                    class="fa fa-trash fa-sm"></i></button> {% endif %}
                                <button class="btn btn-dark btn-sm" onclick="likeComment({{ comm.id }})"><i  class="far fa-thumbs-up mr-2 text-info"></i> 
                            	<span id="commentLikes_{{ comm.id }}" data-url="{% url 'posts:likeacomment' %}" >{{ comm.total_likes }} Like{{comm.total_likes|pluralize}}</span>
                            </button>
                            </h6>
                        </div>
                    </div>
                    {% empty %}
                    <h2 class="text-center text-muted p-5">-No comments yet-</h2>
                    {% endfor %}


                </div>
            </div>








            <div style="background-color: #f4f6f9; border:#f4f6f9;" class="col-lg-4 col-md-5 col-sm-12 offset-0 card h-100 layout-fixed hold-transition">
                <h5 class="text-info text-center py-2"> <i class="fas fa-info-circle text-primary"></i> About {% if post.posted_by == user %} you {% else %} {% if post.posted_by.profile.role is not None %} this {{post.posted_by.profile.get_role_display|capfirst}}-{% endif %}{{post.posted_by.username|capfirst}}'
                    {% endif %}</h5>
                {% if post.posted_by.profile.profile_pik.url is not None %}
                <img class="img-circle img-bordered-sm img-lg mx-auto" src="{{post.posted_by.profile.profile_pik.url}}" alt="{{post.posted_by.username|capfirst}}"> {% else %}
                <img class="img-circle img-bordered-sm img-lg mx-auto" src="{% static 'images/images.jpg' %}" alt="{{post.posted_by.username|capfirst}}"> {% endif %}

                <ul class="list-group list-group-unbordered my-3">
                    <li class="list-group-item">
                        <b>Full name: </b> <a class="float-right">{{ post.posted_by.first_name|capfirst }} {{ post.posted_by.last_name|capfirst }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Role: </b> <a class="float-right">{{ post.posted_by.profile.get_role_display|capfirst }} {{ post.user.last_name|capfirst }}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Joined: </b> <a class="float-right">{{ post.posted_by.date_joined|naturaltime}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Email: </b> <a class="float-right">{{ post.posted_by.email}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Contact: </b> <a class="float-right">{{ post.posted_by.profile.phone_number}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Address: </b> <a class="float-right">{{ post.posted_by.profile.address|capfirst}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Stars: </b> <a class="float-right">{{ post.posted_by.profile.total_stars|intword}}</a>
                    </li>
                    <li class="list-group-item">
                        <b>Experience(yrs): </b> <a class="float-right">{{ post.posted_by.profile.years_of_experiance|intword}}</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

{% endblock content %} {% block script %}
<script>
    function likeComment(id) {
        let url = $('#commentLikes_' + id).data('url')
        $.ajax({
            url: url,
            data: {
                "id": id,
            },
            type: 'GET',
            dataType: 'json',
            success: function(response) {
                let myvar = ""
                if (response.countNow == 1) {
                    myvar = "Like"
                } else {
                    myvar = "Likes"
                }

                $('#commentLikes_' + id).text(response.countNow + ' ' + myvar)
            }
        })
    }


    function deleteCommentNow(id, forPost) {
        let url = $('#commentDelete_' + id).data('url')
        $.ajax({
            url: url,
            data: {
                "id": id,
                "post_id": forPost
            },
            type: 'GET',
            dataType: 'json',
            success: function(response) {
                if (response.result == "ok") {
                    $('#numNow').text(response.countNow)
                    $('#commentbox' + id).fadeOut('slow').remove()
                }

            }
        })
    }


    $('#formforComment').on('submit', function(e) {
        e.preventDefault()

        let data = $(this).serialize()
        let url = $(this).attr('action')
            // alert(data + ' ' + url)
        $.ajax({
            url: url,
            data: data,
            type: 'POST',
            dataType: 'json',
            success: function(response) {
                $('#numNow').text(response.new_num)
                $('#commentSection').load(location.href + ' #commentSection')
                $('#formforComment').trigger('reset')
            }
        })
    })
</script>

{% endblock script %}