posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('forgot_password/', views.forgot, name="forgot"),
    path('recover_password/', views.recover, name="recover"),
    path("posts/like/", views.likeapost, name="likeapost"),
    path("comments/like/", views.likeacomment, name="likeacomment"),
    path("comments/delete/", views.deleteacomment, name="deleteacomment"),
    path("posts/delete/", views.deletepost, name="deletepost"),
    path("posts/add", views.post_a_Post, name="addpost"),
    path("posts/<slug>/details", views.PostDetailView.as_view(), name="single_post"),
    path("posts/<pk>/details/comment", views.AddComment, name="comment_post"),
]

profiler/urls.py
from django.urls import path
from . import views

app_name = 'profile'
urlpatterns = [
    path('', views.UserListView.as_view(), name="index"),
    path('<pk>/', views.SingleUser, name="profile_for"),
    path('upload/', views.UpdateProfileImage, name="update_image"),
    path('auth/reset_password/', views.request_code,
         name="reset_password_with_token"),
    path("auth/provide_token/", views.EnterCodeView.as_view(), name="enter_code"),
    path("<int:code>/recover/", views.ResetPassword, name="recover"),
    path('check_expiriration', views.check_expiriration,
         name='check_expiriration'),
]

yieldUp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('diagonise/', include('diagnosis.urls')),
    path('doctors/', include('doctor.urls')),
    path('users/', include('profiler.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/auths/enter_token.html
{% extends 'basic.html' %} {% block content %}
<div class="login-box">
    <div class="login-logo">
        <a href="{% url 'posts:index' %}"><b>Yield</b>Up</a>
    </div>
    <!-- /.login-logo -->

    <div class="card">
        <div class="card-body login-card-body">
            <div class="alert d-none" id="message"></div>
            <p class="login-box-msg">We have received your request to change your password and sent you an email with a token on the email address you provided on the previous screen, enter that token below to proceed. That token will be valid for only 30 minutes from the time
                of its first issue</p>

            <form action="{% url 'profile:check_expiriration' %}" id="code_form" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="number" minlength="10" id="code" maxlength="10" name="code" class="form-control" placeholder="Enter token">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-password"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-warning btn-block">Verify code</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <p class="mt-3 mb-1">
                <a href="{% url 'posts:login' %}">Login</a>
            </p>
            <p class="mb-0">
                <a href="{% url 'posts:register' %}" class="text-center">Register a new membership</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
{% endblock content %} {% block script %}
<script>
    $("#code_form").submit(function(e) {
        e.preventDefault();
        url = $(this).attr('action');
        data = $("#code_form").serialize();
        code = $("#code").val();
        $.ajax({
            url: url,
            data: data,
            type: 'GET',
            success: function(res) {
                if (res.status) {
                    alert(res.message)
                    window.location.href = `/users/${code}/recover/`;
                } else {
                    alert(res.message)
                }
            }
        })
    })
</script>
{% endblock script %}

templates/auths/forgot_password.html
{% extends 'basic.html' %} {% block content %}
<div class="login-box">
    <div class="login-logo">
        <a href="{% url 'posts:index' %}"><b>Yield</b>Up</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>
            <div class="alert d-none" id="message"></div>

            <form id="ignite_reset" method="post" data-redirect="{% url 'profile:enter_code' %}" action="{% url 'profile:reset_password_with_token' %}">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="email" name="email" required class="form-control" placeholder="Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-warning btn-block" id="btn_submit">Request new password</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <p class="mt-3 mb-1">
                <a href="{% url 'posts:login' %}">Login</a>
            </p>
            <p class="mb-0">
                <a href="{% url 'posts:register' %}" class="text-center">Register a new membership</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
{% endblock content %} {% block script %}
<script>
    $('#ignite_reset').submit(function(e) {
        e.preventDefault()
        data = $(this).serialize()
        url = $(this).attr("action")
        $.ajax({
            url: url,
            data: data,
            type: 'POST',
            beforeSend: function() {
                $('#btn_submit').attr('disabled', true)
                $('#btn_submit').html('<i class="fa fa-spinner fa-spin"></i> Sending...')
            },
            success: function(res) {
                let bg = "success"
                if (!res.status) {
                    bg = "danger"
                }
                $("#message").text(res.message).removeClass('d-none').addClass("alert-" + bg)
                setTimeout(function() {
                    $("#message").fadeOut('slow').addClass("d-none").removeClass("alert-" + bg)
                    if (res.status) {
                        window.location.href = $('#ignite_reset').data("redirect")
                    }
                }, 4000)
            },
            complete: () => {
                $('#btn_submit').attr('disabled', false)
                $('#btn_submit').html('Request new password')
            }


        })

    })
</script>
{% endblock script %}

templates/auths/login.html
{% extends 'basic.html' %} {% block content %}
<div class="login-box">
    <div class="login-logo">
        <a href="{% url 'posts:index' %}" class="text-warning"><b>Yield</b>Up</a>
    </div>
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Sign in to start your session</p>
            <div id="return-messages" class="alert"></div>
            <form action="{% url 'posts:login' %}" method="post" id="test-form10">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="username" placeholder="Username or Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" name="password" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-7">
                        <div class="icheck-primary">
                            <a href="{% url 'profile:reset_password_with_token' %}">I forgot my password</a>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-5">
                        <button type="submit" id="LoginBtn" class="btn btn-warning btn-block">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>


            <p class="mb-0">
                <a href="{% url 'posts:register' %}" class="text-center">Register a new membership</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
{% endblock content %} {% block script %}
<script>
    $(document).on('submit', "#test-form10", function(e) {
        $('#LoginBtn').text("Please wait...")
        e.preventDefault()
        form = $(this).serialize();
        $.ajax({
            type: 'post',
            url: $(this).attr('action'),
            data: form,
            success: function(response) {
                rs = response.result
                cssNow = response.class
                $('#LoginBtn').text("Sign in")
                $('#return-messages').addClass('alert-' + cssNow)
                $('#return-messages').text(rs)
                if (rs == 'Login successfull') {
                    $('#test-form').trigger('reset')
                    window.location.href = '/'
                }
            }
        })
    })
</script>
{% endblock script %}

templates/auths/recover_password.html
{% extends 'basic.html' %} {% block content %}
<div class="login-box">
    <div class="login-logo">
        <a href="{% url 'posts:index' %}"><b>Yield</b>Up</a>
    </div>
    <!-- /.login-logo -->
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">You are only one step a way from your new password, recover your password now. {{ view.kwargs.code }}</p>
            <form action="{% url 'profile:recover' code %}" id="change_form" method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="password" name="new_password" class="form-control" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" name="confirm_password" class="form-control" placeholder="Confirm Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-warning btn-block">Change password</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <p class="mt-3 mb-1">
                <a href="{% url 'posts:login' %}">Login</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
    <span class="d-none field-h" data-url="{% url 'profile:check_expiriration' %}" data-id="{{code}}"></span>
</div>
{% endblock content %} {% block script %}
<script>
    $(document).ready(function() {
        var code = $(".field-h").data("id")
        var url = $(".field-h").data("url")
        $.ajax({
            url: url,
            data: {
                code
            },
            success: (res) => {
                console.log(res)
                if (!res.status) {
                    alert("Your code has already expired, we will redirect you to requesting a new one.")
                    window.location.href = "{% url 'profile:reset_password_with_token' %}"
                }
            }
        })
    })
    $("#change_form").submit(function(e) {
        e.preventDefault()
        var form = $(this)
        var url = form.attr("action")

        var data = form.serialize()
        $.ajax({
            url: url,
            data: data,
            method: "POST",
            success: (res) => {
                if (res.success != "") {
                    alert(res.success)
                    window.location.href = "{% url 'posts:login' %}"
                } else {
                    alert(res.error)
                }
            }
        })
    })
</script>
{% endblock script %}

templates/auths/register.html
{% extends 'basic.html' %}

{% block content %}
<div class="register-box">
  <div class="register-logo">
   <a href="{% url 'posts:index' %}" class="text-warning"><b>Yield</b>Up</a>
 </div>

 <div class="card">
  <div class="card-body register-card-body">
    <p class="login-box-msg">Register a new membership</p>
    <div id="return-messages" class="alert"></div>
    <form action="{% url 'posts:register' %}" method="post" id="test-form">
      {% csrf_token %}
      <div class="input-group mb-3">
        <input type="text" id="fname" class="form-control" oninput ="validateFname()" name="fname" placeholder="First name">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-user-circle"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="text" id="lname" class="form-control" oninput="validateLname()" name="lname" placeholder="Last name">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-user-plus"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="text" id="username" class="form-control" oninput="validateUsername()" name="username" placeholder="Username">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-user-check"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="email" id="email" class="form-control" oninput="validateEmail()" name="email" placeholder="Email">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-envelope"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="password" id="password1" class="form-control" oninput="validatePass1()" name="password1" placeholder="Password">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-lock"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="password" id="password2" class="form-control"  oninput="validatePass2()" name="password2" placeholder="Retype password">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-lock-open"></span>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-7">
          <div class="icheck-primary">
            <input type="checkbox" required id="agreeTerms" name="terms">
            <label for="agreeTerms">
             I agree to the <a>terms</a>
           </label>
         </div>
       </div>
       <!-- /.col -->
       <div class="col-5">
        <button type="submit" id="registerBtn" class="btn btn-warning btn-block">Register</button>
      </div>
      <!-- /.col -->
    </div>
  </form>

  <a href="{% url 'posts:login' %}" class="text-center">I already have a membership</a>
</div>
<!-- /.form-box -->
</div><!-- /.card -->
</div>
{% endblock content %}
{% block script %}
<script type="text/javascript">

  function validateFname(){
    let fname = $('#fname').val()
    if (fname == "") {
      $('#return-messages').text("First name is still empty")
      return false
    }
    else if (fname.length < 3) {
      $('#return-messages').text("First name is still invalid")
      return false
    }
    else{
      $('#return-messages').text("")
      return true
    }
  }

  function validateUsername(){
    let username = $('#username').val()
    if (username == "") {
      $('#return-messages').text("Username is still empty")
      return false
    }
    else if (username.length < 4) {
      $('#return-messages').text("Create a stronger username")
      return false
    }
    else{
      $('#return-messages').text("")
      return true
    }
  }

  function validatePass2(){
    let password2 = $('#password2').val()
    let password1 = $('#password1').val()
    if (password2 != password1) {
      $('#return-messages').text("Please confirm your password")
      return false
    }
    else{
      $('#return-messages').text("")
      return true
    }
  }

   function validatePass1(){
    let password1 = $('#password1').val()
    let lname = $('#lname').val()
    let username = $('#username').val()
    let email = $('#email').val()
    if (password1 == "") {
      $('#return-messages').text("Please create a password")
      return false
    }
    else if (password1.length < 6) {
      $('#return-messages').text("Password is still weak")
      return false
    }
    else if (password1.length >= 6 && password1.length <= 8) {
      $('#return-messages').text("Password is still medium")
      return true
    }
    else if (password1.length > 8) {
      $('#return-messages').text("")
      return true
    }else if (password1 == lname || password1 == email || password1 == username) {
      $('#return-messages').text("Password cannot be similar to any other credentials")
      return false
    }
    else{
      $('#return-messages').text("")
      return true
    }
  }

  function validateLname(){
    let lname = $('#lname').val()
    if (lname == "") {
      $('#return-messages').text("Last name is still empty")
      return false
    }
    else if (lname.length < 3) {
      $('#return-messages').text("Last name is still invalid")
      return false
    }
    else{
      $('#return-messages').text("")
      return true
    }
  }

  function validateEmail(){
    let email = $('#email').val()
    if (email == "") {
      $('#return-messages').text("Email is still empty")
      return false
    }
    else if (email.length < 5) {
      $('#return-messages').text("Email is still invalid")
      return false
    }else if(email.indexOf('@') < 2){
      $('#return-messages').text("Email is still invalid")
      return false
    }else if(email.charAt(email.indexOf('@') + 1) == "." ){
      $('#return-messages').text("Email is still invalid")
      return false
    }
     else if (email.indexOf('.') < 3){
      $('#return-messages').text("Email is still invalid")
      return false
    } else if(email.charAt(email.indexOf('.') + 1) == "" ){
      $('#return-messages').text("Email is still invalid")
      return false
    } else if(email.charAt(email.indexOf('.') + 2) == "" ){
      $('#return-messages').text("Email is still invalid")
      return false
    }
    else{
      $('#return-messages').text("")
      return true
    }
  }



  // function validated(){
  //   
  //   let lname = $('#lname').val()
  //   let username = $('#username').val()
  //   let email = $('#email').val()
  //   let password1 = $('#password1').val()
  //   let password2 = $('#password2').val()

  //   if (fname == "" ) {

  //   }
  // }

  $(document).on('submit', "#test-form", function (e) {
    e.preventDefault()
    $('#registerBtn').text("Please wait...")
    form = $(this).serialize();
    if(!validatePass2){
      alert("Password not matching")
    }else{
    $.ajax({
      type: 'post',
      url: $(this).attr('action'),
      data: form,
      success: function (response) {
       rs = response.result
       cssNow = response.class
       $('#return-messages').addClass('alert-' + cssNow)
       $('#return-messages').text(rs)
       $('#registerBtn').text("Register")
       if (rs == 'Account created successfully, you can now login') {
        $('#test-form').trigger('reset')
        window.location.href = '/login'
      }
    }


  })
  }
  })
</script>
{% endblock script %}