diagnosis/urls.py
from django.urls import path
from diagnosis import views

app_name = 'diagonise'
urlpatterns = [
    path('', views.DiagoniseView.as_view(), name="index"),
    path('test_response/', views.analyse, name="analyse"),
    path('responses/', views.resultsPage, name="results"),
]

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('forgot_password/', views.forgot, name="forgot"),
    path('recover_password/', views.recover, name="recover"),
    path("posts/like/", views.likeapost, name="likeapost"),
    path("comments/like/", views.likeacomment, name="likeacomment"),
    path("comments/delete/", views.deleteacomment, name="deleteacomment"),
    path("posts/delete/", views.deletepost, name="deletepost"),
    path("posts/add", views.post_a_Post, name="addpost"),
    path("posts/<slug>/details", views.PostDetailView.as_view(), name="single_post"),
    path("posts/<pk>/details/comment", views.AddComment, name="comment_post"),
]

yieldUp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('diagonise/', include('diagnosis.urls')),
    path('doctors/', include('doctor.urls')),
    path('users/', include('profiler.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

diagnosis/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import validate_image_file_extension

# Create your models here.
class Diagnosis(models.Model):
    crop_type = [
        ("cs", "Cassava"),
        ("bn", "Bean"),
    ]
    farmer = models.ForeignKey(User, on_delete=models.CASCADE)
    predicate_disease = models.CharField(max_length = 100,  blank=True, null=True)
    did_work = models.BooleanField(default = False)
    diagnosis_text = models.TextField(blank=True, null=True)
    type_of_test = models.CharField(max_length = 10, choices = crop_type)
    feedbacks = models.TextField(max_length = 1000, null = True, blank = True)
    tested_on = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        self.farmer.username

diagnosis/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import Diagnosis
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

# from .beanclassification import predictResult, test_dataset
class DiagoniseView(TemplateView):
	template_name = 'diagnosis/index.html'

@login_required(login_url = '/login/')
def resultsPage(request, crop_type):
	# form = DiagnosisImageForm()
	return render(request, 'diagnosis/fileUpload.html', {"crop":crop_type})


@login_required(login_url = '/login/')
def analyse(request):
	if request.method == 'POST':
		code = request.POST.get("code").lower()
		user = request.user
		mytype = "bn"
		disease = ""
		is_fine = False
		mydiagText = ""
		msg = ""
		if code == '#0brd':
			disease = "Bean rust"
			mydiagText = "Your bean sample has been infected with <b>Bean rust</b>. <br> Bean rust can be controlled by using a combination of management practices: Use clean bean seeds originating from non-diseased plants or from certified seed dealers. Using clean seeds prevents spreading of rust disease. We have found some solutions on <a href ='https://www.growveg.com/plant-diseases/us-and-canada/bean-rust/'/>here<a> and <a href='https://homeguides.sfgate.com/rid-rust-beans-28584.html'>here</a>"
			is_fine = True
		elif code == '#1alsd':
			disease = "Angular-leaf spot"			
			mydiagText = "Your bean sample has been diagnised with <b>Angular-leaf spot</b>.<br> It is characterised by: Leaves develop small, angular, brown or straw-colored spots with a yellow halo. Leaf spots dry and drop out, leaving irregularly shaped holes in the leaves. We found out useful resources on <a href ='https://extension.umn.edu/diseases/angular-leaf-spot'/>here<a> and <a href='https://www.gardeningknowhow.com/plant-problems/disease/treating-angular-leaf-spot.htm'>here</a>"
			is_fine = True
		elif code == '#2hl':
			disease = "Healthy"
			is_fine = True
			mydiagText = "Your bean sample has been found <b>healthy</b>."
		else:
			is_fine = False
			msg = "The code you sent is invalid, are you sure you tested?"
		if is_fine:
			save_diag = Diagnosis(
					farmer = user,
					predicate_disease = disease, 
					diagnosis_text = mydiagText,
					type_of_test = mytype, 
				)

			myresp = save_diag.save()
			all_tests = Diagnosis.objects.filter(farmer = request.user).order_by('-tested_on')
			respo = Diagnosis.objects.filter(farmer = user).order_by('-tested_on')[:1]
			context = {
				"resp": respo[0],
				"all_tests": all_tests
			}
			return render(request, 'diagnosis/feedback.html', context)
		else:
			context = {
				"msg": msg,
			}
			return render(request, 'diagnosis/index.html', context)


def resultsPage(request):
	context = {
		"all_tests" : Diagnosis.objects.filter(farmer = request.user).order_by('-tested_on')
		 }
	return render(request, 'diagnosis/feedback.html', context)

templates/diagnosis/feedback.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="content">
      <!-- <div class="container "> -->
      	<h5 class="font-weight-bold p-3 text-muted text-centered">These are the samples you have tested with us in their order from the most lates</h5>
            <a href="{% url 'diagonise:index' %}" class="btn text-info"><i class="fa fa-arrow-left"></i> Back to testing</a>

            <div class="row mx-auto">
              {% if resp %}
        <div class="card col-md-3 bg-dark text-muted">
         <div class="p-1">
          <h6 class="text-muted font-weight-bold p-2">Your recent test results.</h6>
          <h6 ><span class="font-weight-bold">Type:</span> {{resp.get_type_of_test_display|capfirst}}</h6>
          <hr>
          <h6><span class="font-weight-bold">Results:</span> {{resp.predicate_disease|capfirst}}</h6>
          <hr>
          <h6><span class="font-weight-bold">Diagnosis:</span> {{resp.diagnosis_text|capfirst|safe}}</h6>
          </div>
         </div>
         {% endif %}
              <div class="{% if resp %} col-md-9 {% else %} ml-md-1 col-md-12 {% endif %}">
                  <div class="text-left text-lg text-muted p-2 ">Your history tests</div>
                <div class="row">

      	{% for sample in all_tests %}
            <div class="card {% if not resp %} col-md-5 col-sm-12 ml-md-1 {% else %} col-sm-12 col-md-6 {% endif %}" >
                  
                <div class="card-body">
                    <h5>
                    <span class="font-weight-bold">Result on:</span> {{ sample.tested_on|date:"d, M, Y" }} at {{ sample.tested_on|date:"g:i A" }}</h5>
                    <h5><span class="font-weight-bold">Results:</span> {{ sample.predicate_disease }}</h5>
                    <p class="card-text">
                      <span class="font-weight-bold">Suggested remmedy</span>: &nbsp;{{ sample.diagnosis_text|capfirst|safe }}</p>
                    <!-- <a href="#" class="btn btn-primary">Has this worked for you?</a> -->
              </div>
        </div>
        {% empty %}
        <div class="alert alert-info w-100 text-center p-3">You haven't tested anything!!</div>
        {% endfor %}
        </div>
        </div>
        
        </div>
  <!-- </div> -->
</section>
{% endblock content %}

templates/diagnosis/index.html
{% extends 'base.html' %}

{% block content %}

<div class="text-center mt-5 pt-5 container">
	<a href="{% url 'diagonise:results' %}" class="btn text-info">Continue to your previous tests &nbsp;<i class="fa fa-arrow-right"></i></a>
	<div class="card p-3">
		<h3 class="my-5 text-muted card-title">Welcome to the diagnosis section!</h3>
		<div class="card-body text-muted">
			<p>Hello {{user.username|capfirst}}, due to the need to have live pictures/photos we have shifted this servive to our <a href="https://drive.google.com/drive/folders/1vpTTZJqTJKMHYYDtcOMPfoy-JzGZO0l3">Mobile app.</a> </p>
			<p>
				From the mobile app, you will take a live photo from your garden, then it will do the testing, the results will be fed here for any remedies/steps to take up next. 
			</p>
			<p>
				We have left our web app majorly for networking with our farmers.
			</p>
			<p>
				Already done your prediction, and wondering what next??
				<p>
				If you have your results, click <span class="text-success">Proceed to remedy</span> below to proceed. 
				</p>
			</p>

			<blockquote class="text-success">Note that the response code you enter below should be obtained from your mobile app's response after testing.</blockquote>

			{% if msg != "" %}
			<span class="text-danger">{{msg}}</span>
			{% else %}
			{% endif %}
			<div class="card-footer">
				<form class="float-left" id="codeForm" action="{% url 'diagonise:analyse' %}" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<label for="disease">Enter the code from the mobile app test below.</label>
						<input type="text" id="disease" name="code" placeholder="Enter code here" class="form-control">
					</div>
				</form>
				<button id="submitDisease" class="btn btn-success btn-user float-right disabled">
					Proceed to remedy <i class="fa fa-arrow-right"></i>
				</button>
			</div>
		</div>
	</div>
</div>
{% endblock content %}
{% block script %}
	<script>
		$("#disease").keyup(function () {
			if ($(this).val() == "") {
				$('#submitDisease').addClass('disabled')
			}else{
				$('#submitDisease').removeClass('disabled')
			}
		})

		// submit the response for remedies
		$('#submitDisease').click(function(e){
			$('#codeForm').trigger('submit')
		})

	</script>
{% endblock script %}